#!/bin/bash

# Auto-Build Environment Setup for User Management Hooks Completion
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "User Management Hooks Completion - Spec 004"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Frontend Development Server..."
cd frontend
npm run dev &
FRONTEND_PID=$!

wait_for_service 3000 "Frontend (Next.js)"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Development Commands:"
echo "  cd frontend && npm run dev           # Start dev server"
echo "  cd frontend && npm run test:hooks    # Run hook tests"
echo "  cd frontend && npm run test:integration  # Run integration tests"
echo "  cd frontend && npm run type-check    # TypeScript type checking"
echo ""
echo "Target File:"
echo "  frontend/src/hooks/useUsers.ts"
echo ""
echo "Pattern Files:"
echo "  frontend/src/hooks/useProducts.ts"
echo "  frontend/src/lib/supabase/client.ts"
echo "  frontend/__tests__/integration/user-management-flow.test.tsx"
echo ""
echo "Press Ctrl+C to stop all services"
echo "========================================"

# Wait for Ctrl+C
trap "echo 'Stopping services...'; kill $FRONTEND_PID 2>/dev/null; exit" SIGINT SIGTERM
wait
